name: Apply Dev

on:
  push:
    branches:
      - not

jobs:
  apply:
    name: Apply Dev
    uses: ./.github/workflows/apply.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
    secrets: inherit
