# 再利用可能なワークフロー: Terraform Apply
name: Apply

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 対象の環境

env:
  TEST: ${{ vars.TEST }}
  TAG: apply

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo
        run: echo ${{ inputs.environment }}
      - name: echo
        run: echo ${{ env.TEST }}
      - name: echo
        run: echo ${{ env.TAG }}
