name: Apply Prod

on:
  push:
    branches:
      - not

jobs:
  apply:
    name: Apply Prod
    uses: ./.github/workflows/apply.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
    secrets: inherit
