on:
  push:
    branches:
      - main

env:
  TARGET_DIR: terraform/environment/dev

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{env.TARGET_DIR}}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{env.TARGET_DIR}}
        run: terraform plan
