on:
  push:
    branches:
      - main

env:
  TARGET_DIR: terraform/env/dev

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - run: ls

      - working-directory: ${{env.TARGET_DIR}}
        run: ls

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan
