# 再利用可能なワークフロー: Terraform Plan
name: Plan

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 対象の環境

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SHARED_ROLE_ARN: ${{ secrets.AWS_SHARED_ROLE_ARN }}
  TEST: ${{ vars.TEST }}

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: check
        run: echo ${{ env.TEST }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_SHARED_ROLE_ARN }}
      - name: check
        run: aws s3 ls
