name: Plan Dev

on:
  pull_request:
    branches:
      - develop

jobs:
  plan:
    name: Plan Dev
    uses: ./.github/workflows/plan.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
    with:
      environment: dev
    secrets: inherit
