name: Plan Prod

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Plan Prod
    uses: ./.github/workflows/plan.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
    with:
      environment: prod
    secrets: inherit
