name: Plan Dev

on:
  pull_request:
    branches:
      - develop

jobs:
  plan:
    name: Plan Dev
    uses: ./.github/workflows/plan.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
    secrets: inherit
