# 再利用可能なワークフロー: Terraform Plan
name: Plan

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 対象の環境(dev, stg, prod)

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SHARED_ROLE_ARN: ${{ secrets.AWS_SHARED_ROLE_ARN }}
  TARGET_DIR: "./terraform/environment/${{ inputs.environment }}"

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: TEST
        run: echo ${{ env.TARGET_DIR }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_SHARED_ROLE_ARN }}

      - name: check
        run: aws s3 ls

      - name: Get Terraform version
        id: terraform-version
        run: cat .terraform-version

      - name: Test
        run: echo ${{steps.terraform-version.outputs.terraform-version}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        working-directory: ${{ env.TARGET_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TARGET_DIR }}
        run: terraform plan
