name: Plan Prod

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan Prod
    uses: ./.github/workflows/plan.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
    secrets: inherit
