# 再利用可能なワークフロー: Terraform Plan
name: Plan

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 対象の環境(dev, stg, prod)

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SHARED_ROLE_ARN: ${{ secrets.AWS_SHARED_ROLE_ARN }}
  TARGET_DIR: "./terraform/environment/${{ inputs.environment }}"

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_SHARED_ROLE_ARN }}

      - name: Get Terraform version
        id: terraform-version
        run: echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.value }}

      - name: Terraform Init
        working-directory: ${{ env.TARGET_DIR }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TARGET_DIR }}
        run: terraform plan

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.43.1

      - name: aqua Init
        run: aqua init

      - name: Setup tfcmt
        run: aqua g -i suzuki-shunsuke/tfcmt

      - name: aqua Install
        run: aqua i

      - name: tfcmt
        run: tfcmt -v
