name: Prod Plan

on:
  pull_request:
    branches:
      - not

env:
  TARGET_DIR: terraform/environment/dev

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_SHARED_ASSUME_ROLE_ARN}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{env.TARGET_DIR}}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{env.TARGET_DIR}}
        run: terraform plan
