# 再利用可能なワークフロー: Terraform Plan
name: Plan-test

on:
  pull_request:
    branches:
      - develop

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SHARED_ROLE_ARN: ${{ secrets.AWS_SHARED_ROLE_ARN }}

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_SHARED_ROLE_ARN }}
      - name: check
        run: aws s3 ls
